# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import sat_score_pb2 as sat__score__pb2


class SATScoreInfoStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetScore = channel.unary_unary(
        '/satscore.SATScoreInfo/GetScore',
        request_serializer=sat__score__pb2.RequestScore.SerializeToString,
        response_deserializer=sat__score__pb2.Score.FromString,
        )
    self.AverageScore = channel.stream_stream(
        '/satscore.SATScoreInfo/AverageScore',
        request_serializer=sat__score__pb2.RequestScore.SerializeToString,
        response_deserializer=sat__score__pb2.AveScore.FromString,
        )


class SATScoreInfoServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetScore(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AverageScore(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SATScoreInfoServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetScore': grpc.unary_unary_rpc_method_handler(
          servicer.GetScore,
          request_deserializer=sat__score__pb2.RequestScore.FromString,
          response_serializer=sat__score__pb2.Score.SerializeToString,
      ),
      'AverageScore': grpc.stream_stream_rpc_method_handler(
          servicer.AverageScore,
          request_deserializer=sat__score__pb2.RequestScore.FromString,
          response_serializer=sat__score__pb2.AveScore.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'satscore.SATScoreInfo', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
